<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>StorageChronicle.UI.Settings</RootNamespace>
    <AssemblyName>StorageChronicle.UI.Settings</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\StorageChronicle.Settings\StorageChronicle.Settings.csproj" />
    <PackageReference Include="CommunityToolkit.Mvvm" />
  </ItemGroup>
</Project>
