<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-windows10.0.19041.0</TargetFramework>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <RootNamespace>StorageChronicle.Platform.Windows.FileSystem</RootNamespace>
    <AssemblyName>StorageChronicle.Platform.Windows.FileSystem</AssemblyName>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\StorageChronicle.Platform.Abstractions\StorageChronicle.Platform.Abstractions.csproj" />
  </ItemGroup>
</Project>
