<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><OutputType>WinExe</OutputType><RootNamespace>StorageChronicle.UI.Desktop</RootNamespace><AssemblyName>StorageChronicle.UI.Desktop</AssemblyName><ApplicationIcon /></PropertyGroup>
  <ItemGroup><ProjectReference Include="..\StorageChronicle.UI.Shared\StorageChronicle.UI.Shared.csproj" /><PackageReference Include="Avalonia.Desktop" /><PackageReference Include="Avalonia.Themes.Fluent" /><PackageReference Include="Avalonia.Fonts.Inter" /></ItemGroup>
</Project>
