<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework Condition="'$(OS)' == 'Windows_NT'">net10.0-windows10.0.19041.0</TargetFramework>
    <TargetFramework Condition="'$(OS)' != 'Windows_NT'">net10.0</TargetFramework>
    <RootNamespace>StorageChronicle.Benchmarks</RootNamespace>
    <AssemblyName>StorageChronicle.Benchmarks</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\StorageChronicle.Projection\StorageChronicle.Projection.csproj" />
    <ProjectReference Include="..\..\src\StorageChronicle.State\StorageChronicle.State.csproj" />
    <ProjectReference Include="..\..\src\StorageChronicle.Storage\StorageChronicle.Storage.csproj" />
    <ProjectReference Include="..\..\src\StorageChronicle.ExternalMedia\StorageChronicle.ExternalMedia.csproj" />
    <ProjectReference Include="..\..\src\StorageChronicle.Platform.Windows.Ntfs\StorageChronicle.Platform.Windows.Ntfs.csproj" Condition="'$(OS)' == 'Windows_NT'" />
    <PackageReference Include="BenchmarkDotNet" />
  </ItemGroup>
  <ItemGroup Condition="'$(OS)' != 'Windows_NT'">
    <Compile Remove="MftBenchmarks.cs" />
  </ItemGroup>
</Project>
